
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Install ssl certificate for HTTPS and set up reverse proxy
http:
  server_port: 8123
  #ssl_certificate: /ssl/origin.crt
  #ssl_key: /ssl/origin.key
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.4.152   # IP of your reverse proxy
    - 172.16.0.0/12   # (optional) Cloudflare proxy IPs if using Cloudflare Tunnel


# Set external URL
homeassistant:
  external_url: "https://niwotha.katesconsult.com"

# Include definitiations for various entities
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Define input numbers
input_number: !include input_number.yaml

# Define mock shades (covers)
#cover: !include covers.yaml

# Define sensors for displaying time, weather and vehicle information
template: !include templates.yaml

# Configure wallbox controls and sensors
rest_command: !include wallbox_apis.yaml
sql: !include wallbox_sql.yaml


# Clean up database (home-assistant_v2.db)
recorder:
  purge_keep_days: 7
  auto_purge: true

                        